const products = [
  {
    id: 1,
    title: "Diamond Ring",
    price: "$2,499",
    category: "Rings",
    image: "../src/assets/ring.jpg",
  },
  {
    id: 2,
    title: "Gold Necklace",
    price: "$3,999",
    category: "Necklaces",
    image: "../src/assets/necklace.jpg",
  },
  {
    id: 3,
    title: "Luxury Earrings",
    price: "$1,799",
    category: "Earrings",
    image: "../src/assets/earring.jpg",
  },
  {
    id: 4,
    title: "Ruby Bracelet",
    price: "$1,299",
    category: "Bracelets",
    image: "../src/assets/bracelet.jpg",
  },
  {
    id: 5,
    title: "Diamond Ring",
    price: "$2,499",
    category: "Rings",
    image: "../src/assets/ring.jpg",
  },
  {
    id: 6,
    title: "Diamond Ring",
    price: "$2,499",
    category: "Rings",
    image: "../src/assets/ring.jpg",
  },
  {
    id: 7,
    title: "Diamond Ring",
    price: "$2,499",
    category: "Rings",
    image: "../src/assets/ring.jpg",
  },
  {
    id: 8,
    title: "Diamond Ring",
    price: "$2,499",
    category: "Rings",
    image: "../src/assets/ring.jpg",
  },
  {
    id: 9,
    title: "Diamond Ring",
    price: "$2,499",
    category: "Rings",
    image: "../src/assets/ring.jpg",
  },
  {
    id: 10,
    title: "Ruby Bracelet",
    price: "$1,299",
    category: "Bracelets",
    image: "../src/assets/bracelet.jpg",
  },
  {
    id: 11,
    title: "Ruby Bracelet",
    price: "$1,299",
    category: "Bracelets",
    image: "../src/assets/bracelet.jpg",
  },
  {
    id: 12,
    title: "Ruby Bracelet",
    price: "$1,299",
    category: "Bracelets",
    image: "../src/assets/bracelet.jpg",
  },
  {
    id: 13,
    title: "Ruby Bracelet",
    price: "$1,299",
    category: "Bracelets",
    image: "../src/assets/bracelet.jpg",
  },
  {
    id: 14,
    title: "Gold Necklace",
    price: "$3,999",
    category: "Necklaces",
    image: "../src/assets/necklace.jpg",
  },
  {
    id: 15,
    title: "Gold Necklace",
    price: "$3,999",
    category: "Necklaces",
    image: "../src/assets/necklace.jpg",
  },
  {
    id: 16,
    title: "Gold Necklace",
    price: "$3,999",
    category: "Necklaces",
    image: "../src/assets/necklace.jpg",
  },
  {
    id: 17,
    title: "Gold Necklace",
    price: "$3,999",
    category: "Necklaces",
    image: "../src/assets/necklace.jpg",
  },
  {
    id: 18,
    title: "Luxury Earrings",
    price: "$1,799",
    category: "Earrings",
    image: "../src/assets/earring.jpg",
  },
  {
    id: 19,
    title: "Luxury Earrings",
    price: "$1,799",
    category: "Earrings",
    image: "../src/assets/earring.jpg",
  },
  {
    id: 20,
    title: "Luxury Earrings",
    price: "$1,799",
    category: "Earrings",
    image: "../src/assets/earring.jpg",
  },
  {
    id: 21,
    title: "Luxury Earrings",
    price: "$1,799",
    category: "Earrings",
    image: "../src/assets/earring.jpg",
  },
  {
    id: 22,
    title: "Luxury Earrings",
    price: "$1,799",
    category: "Earrings",
    image: "../src/assets/earring.jpg",
  },
];

export default products;
